# Generated by Django 4.0.1 on 2022-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
